; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = megaatmega2560
build_dir = .pio-build

[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
build_src_filter = +<*> -<ir_calibrate.cpp> -<scan360.cpp> -<light_detection_test.cpp> -<light_detection_homing.cpp> -<ultrasonic_test.cpp>
lib_deps =
    arduino-libraries/Servo
    adafruit/Adafruit BNO08x

[env:ir_calibrate]
platform = atmelavr
board = megaatmega2560
framework = arduino
build_src_filter = -<*> +<ir_calibrate.cpp>
monitor_speed = 115200

[env:scan360]
platform = atmelavr
board = megaatmega2560
framework = arduino
lib_deps =
    arduino-libraries/Servo
    adafruit/Adafruit BNO08x
build_src_filter = +<*> -<main.cpp> -<fsm.cpp> -<ir_calibrate.cpp> -<light_detection_test.cpp> -<light_detection_homing.cpp> -<ultrasonic_test.cpp>
monitor_speed = 115200

[env:light_detection_test]
platform = atmelavr
board = megaatmega2560
framework = arduino
lib_deps =
    arduino-libraries/Servo
    adafruit/Adafruit BNO08x
build_src_filter = +<*> -<main.cpp> -<fsm.cpp> -<ir_calibrate.cpp> -<scan360.cpp> -<light_detection_homing.cpp> -<ultrasonic_test.cpp>
monitor_speed = 115200

[env:light_detection_homing]
platform = atmelavr
board = megaatmega2560
framework = arduino
lib_deps =
    arduino-libraries/Servo
    adafruit/Adafruit BNO08x
build_src_filter = +<*> -<main.cpp> -<fsm.cpp> -<ir_calibrate.cpp> -<scan360.cpp> -<light_detection_test.cpp> -<ultrasonic_test.cpp>
monitor_speed = 115200

[env:ultrasonic_test]
platform = atmelavr
board = megaatmega2560
framework = arduino
lib_deps =
    adafruit/Adafruit BNO08x
build_src_filter = -<*> +<ultrasonic_test.cpp> +<percepetion.cpp>
monitor_speed = 115200
